## Working with JSON/SQL

In [1]:
import pandas as pd

## Working with JSON

JSON (JavaScript Object Notation) is a lightweight text-based format used to store and exchange data between applications. It represents data using key–value pairs and is commonly used in APIs, web applications, and data analysis.

Example:

{
    "name": "Uday",
    "age": 20
}

In [2]:
pd.read_json(r"C:\Users\udaya\Downloads\train.json")

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [3]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/USD')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
USD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,USD,2026-05-27,1779840001,1.00
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,USD,2026-05-27,1779840001,3.67
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,USD,2026-05-27,1779840001,63.36
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,USD,2026-05-27,1779840001,82.08
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,USD,2026-05-27,1779840001,367.72
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,USD,2026-05-27,1779840001,238.72
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,USD,2026-05-27,1779840001,16.37
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,USD,2026-05-27,1779840001,18.79
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,USD,2026-05-27,1779840001,26.41
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,USD,2026-05-27,1779840001,26.41

## Working  with SQL

SQL (Structured Query Language) is a standard language used to create, manage, retrieve, and manipulate data stored in relational databases such as MySQL, PostgreSQL, and SQL Server.

Example:

SELECT * FROM students;

#### %pip install mysql.connector 
It is a Jupyter Notebook command used to install the MySQL Connector package, which allows Python programs to connect and interact with MySQL databases.

In [4]:
%pip install mysql.connector

Requirement already satisfied: mysql.connector in c:\Users\udaya\anaconda3\Lib\site-packages (2.2.9)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import mysql.connector

In [7]:
conn = mysql.connector.Connect(host='localhost',user='root',password='',database='world')

#### pd.read_sql_query() is a Pandas function used to execute an SQL query and directly load the result into a Pandas DataFrame for analysis.

Example:

import pandas as pd

query = "SELECT * FROM employees"

df = pd.read_sql_query(query, connection)

In [ ]:

df = pd.read_sql_query("SELECT * FROM city WHERE CountryCode LIKE 'IND'",conn)

C:\Users\udaya\AppData\Local\Temp\ipykernel_20296\2443915290.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("SELECT * FROM city WHERE CountryCode LIKE 'IND'",conn)

In [13]:
df

       ID                Name CountryCode        District  Population
0    1024     Mumbai (Bombay)         IND     Maharashtra    10500000
1    1025               Delhi         IND           Delhi     7206704
2    1026  Calcutta [Kolkata]         IND    West Bengali     4399819
3    1027    Chennai (Madras)         IND      Tamil Nadu     3841396
4    1028           Hyderabad         IND  Andhra Pradesh     2964638
..    ...                 ...         ...             ...         ...
336  1360        Ambala Sadar         IND         Haryana       90712
337  1361          Baidyabati         IND    West Bengali       90601
338  1362               Morvi         IND         Gujarat       90357
339  1363             Raigarh         IND     Chhatisgarh       89166
340  1364            Vejalpur         IND         Gujarat       89053

[341 rows x 5 columns]